name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t firstimage:v1 --file dockerfile . 
    - name: Docker tag and Docker push
      run: |
        docker tag firstimage:v1 ${{secrets.DOCKER_USER}}/dockerimage:v1
        docker push ${{secrets.DOCKER_USER}}/dockerimage:v1
