name: GITHUB_CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
        
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
   
      - name: docker login
        env:
          DOCKER_USERNAME_1: ${{secrets.DOCKER_USERNAME_1}}
          OC_USERNAME: ${{secrets.OC_USERNAME}}
          OC_PASSWORD: ${{secrets.OC_PASSWORD}}
        run: |
             docker login -u $DOCKER_USERNAME_1 --password $(oc whoami -t) default-route-openshift-image-registry.apps.ocp4.eidikointernal.com
      - name: Build the Docker image
        run: docker build -t devops:v1 --file dockerfile . 
      - name: oc login,oc project,Docker tag & Docker push
        run: |
            /usr/local/bin/ && ./oc login -u $OC_USERNAME -p $OC_PASSWORD --insecure-skip-tls-verify=true
            /usr/local/bin/ && ./oc project manojprod
            docker tag devops:v1 default-route-openshift-image-registry.apps.ocp4.eidikointernal.com/manojprod/devopsimage:v1
            docker push default-route-openshift-image-registry.apps.ocp4.eidikointernal.com/manojprod/devopsimage:v1
            /home/bandaru/Downloads/devshift.sh
