name: SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  
jobs:
  build:
    runs-on: self-hosted

    steps: 
          - uses: actions/checkout@master
          - name: SonarQube Scan
            uses: kitabisa/sonarqube-action@master
            with:
             projectBaseDir: "Application1"
             projectKey: "New_Repo"
             projectName: "New_Repo"
             projectVersion: "v0.0.1"
             
         
               
