name: SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  
jobs:
  build:
    runs-on: self-hosted

    steps: 
          - uses: actions/checkout@master
          - name: SonarQube Scan
            uses: kitabisa/sonarqube-action@v1.1.0
            with:
             host.url: ${{ secrets.SONARQUBE_HOST }}
             login: ${{ secrets.SONARQUBE_TOKEN }}
          - name: sonar-scanner
            run: sonar-scanner
               -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
               -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}
               -Dsonar.sources=Application1
               -Dsonar.projectKey=New_Repo
               -Dsonar.sourcesEncoding=UTF-8 
         
               
