name: RakBank_CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  
jobs:
  build:
    runs-on: self-hosted

    steps: 
        - name: Run sonarqube
          uses: kitabisa/sonarqube-action@master
          with:
            sonar.projectKey: New_Repo
            sonar.projectName: New_Repo
            sonar.projectVersion: v0.0.1
            sonar.sources: /root/Application1
            sonar.sourceEncoding: UTF-8
               
