name: RakBank_CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  
jobs:
  build:
    runs-on: self-hosted

    steps: 
        - name: Run sonarqube
          uses: kitabisa/sonarqube-action@master
          with:
            projectBaseDir: "/root/Application1"
            projectKey: "New_Repo"
            projectName: "New_Repo"
            projectVersion: "v0.0.1"
               
