name: Publish GitHub Actions Artifacts 

on:
  push:
    branches: [ main ]

jobs:
       
  archive-build-artifacts:
    runs-on: self-hosted
    steps:
        
      - name: Nexus Repo Publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }} 
          NEXUS_REPOSITORY_URL: ${{ secrets.NEXUS_REPOSITORY_URL }}
        run: | 
             curl -v -u$NEXUS_USER:$NEXUS_PASSWORD /home/bandaru/Music/Application1.bar $NEXUS_REPOSITORY_URL
             
