name: Publish GitHub Actions Artifacts 

on:
  push:
    branches: [ main ]

jobs:
       
  archive-build-artifacts:
    runs-on: self-hosted
    steps:
        
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: http://192.168.2.225:8081/repository/devops/
          username: admin
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: raw
          repository: devops
          filename: Application1.bar
        run: | 
             /home/bandaru/Music/Application1.bar
             
