name: SonarQube

on: push

jobs:
  sonarQubeTrigger:
    name: SonarQube_Trigger
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: SonarQube_Scan
      uses: kitabisa/sonarqube-action@master
      with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectBaseDir: "Application1"
          projectKey: "New_Repo"
          projectName: "New_Repo"
          projectVersion: "v0.0.1"
    
         
        
        
        
  
    
         
