name: sonarqube

on: push

jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: SonarQube_Scan
      uses: kitabisa/sonarqube-action@master
      with:
          projectBaseDir: "/root/Application1"
          projectKey: "New_Repo"
          projectName: "New_Repo"
          projectVersion: "v0.0.1"
    
         
        
        
        
  
    
         
