name: Sonarqube

on: push

jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        sonar.projectKey: New_Repo
        sonar.projectName: New_Repo
        sonar.projectVersion: 1.0
        sonar.sources: /root/Application1
        
        
  
    
         
