name: Sonarqube_scanning

on: push

jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
    - name: sonarscanner
      run: sonar-scanner -Dsonar.projectKey=New_Repo -Dsonar.sources=. -Dsonar.host.url=http://localhost:9000 -Dsonar.login=387ddb2cee68dd086b2bec76760d32bffe4a6402 -Dsonar.log.console=true -Dsonar.projectBaseDir=/root/Application1
