name: Sonarqube

on: push

jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
    - name: sonarscanner
      run: 
        cd /home/bandaru/Downloads/sonar-scanner-4.6.2.2472-linux/bin &&
         sonar.projectKey=New_Repo
         sonar.projectName=New_Repo
         sonar.projectVersion=1.0
         sonar.sources=/root/Application1
         sonar.host.url=http://192.168.1.59:9000
        
  
    
         
