name: Sonarqube

on: push

jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
    - name: sonarscanner
      run: sonar-scanner -Dsonar.projectKey=/rootApplication1 -Dsonar.projectName=Bharath -Dsonar.projectVersion=1.0 -Dsonar.sources=/root/Application1 -Dsonar.sourceEncoding=UTF-8
         
