name: Sonarqube_scanning

on: push

jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
    - name: sonarscanner
      run: sonar-scanner -Dsonar.projectKey=New_Repo -Dsonar.projectName=New_Repo -Dsonar.sources=/root/Application1 -Dsonar.sourcesEncoding=UTF-8
