name: Sonarqube_scanning

on: push

jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
    - name: sonarscanner
      env:
        SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECTKEY: ${{ secrets.SONAR_PROJECTKEY }}
        TOKEN: ${{ secrets.TOKEN }}
      run: sonar-scanner
          -Dsonar.host.url=${{ secrets.SONARQUBE_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.scm.provider=git
          -Dsonar.sourcesEncoding=UTF-8
